// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZeroHour.Server.Data;

#nullable disable

namespace ZeroHour.Server.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresGameDbContext))]
    [Migration("20260808093152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZeroHour.Server.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short?>("AgeDeclared")
                        .HasColumnType("smallint")
                        .HasColumnName("age_declared");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_provider");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<long?>("BannedUntil")
                        .HasColumnType("bigint")
                        .HasColumnName("banned_until");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_login_at");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_players_device");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_players_email");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("ZeroHour.Server.Data.PlayerState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AllianceId")
                        .HasColumnType("bigint")
                        .HasColumnName("alliance_id");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("integer")
                        .HasColumnName("config_version");

                    b.Property<int>("HqLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("hq_level");

                    b.Property<long>("LastResolvedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_resolved_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<long>("Power")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("power");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resources");

                    b.Property<long?>("ShieldUntil")
                        .HasColumnType("bigint")
                        .HasColumnName("shield_until");

                    b.Property<int>("Stamina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("stamina");

                    b.Property<int>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    b.Property<int?>("TileX")
                        .HasColumnType("integer")
                        .HasColumnName("tile_x");

                    b.Property<int?>("TileY")
                        .HasColumnType("integer")
                        .HasColumnName("tile_y");

                    b.Property<int>("VipLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vip_level");

                    b.Property<long>("VipPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("vip_points");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId")
                        .HasDatabaseName("ix_ps_alliance");

                    b.HasIndex("PlayerId", "StateId")
                        .IsUnique()
                        .HasDatabaseName("ux_ps_player_state");

                    b.HasIndex("StateId", "Power")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ps_power");

                    b.HasIndex("StateId", "TileX", "TileY")
                        .HasDatabaseName("ix_ps_tile");

                    b.ToTable("player_states", (string)null);
                });

            modelBuilder.Entity("ZeroHour.Server.Data.PlayerState", b =>
                {
                    b.HasOne("ZeroHour.Server.Data.Player", "Player")
                        .WithMany("States")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ZeroHour.Server.Data.Player", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
