// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeroHour.Server.Data;

#nullable disable

namespace ZeroHour.Server.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteGameDbContext))]
    partial class SqliteGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ZeroHour.Server.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<short?>("AgeDeclared")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age_declared");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_provider");

                    b.Property<string>("BanReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("ban_reason");

                    b.Property<long?>("BannedUntil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("banned_until");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_login_at");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_players_device");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_players_email");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("ZeroHour.Server.Data.PlayerState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("AllianceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alliance_id");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("config_version");

                    b.Property<int>("HqLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("hq_level");

                    b.Property<long>("LastResolvedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_resolved_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id");

                    b.Property<long>("Power")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("power");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resources");

                    b.Property<long?>("ShieldUntil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shield_until");

                    b.Property<int>("Stamina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100)
                        .HasColumnName("stamina");

                    b.Property<int>("StateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_id");

                    b.Property<int?>("TileX")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tile_x");

                    b.Property<int?>("TileY")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tile_y");

                    b.Property<int>("VipLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("vip_level");

                    b.Property<long>("VipPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("vip_points");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId")
                        .HasDatabaseName("ix_ps_alliance");

                    b.HasIndex("PlayerId", "StateId")
                        .IsUnique()
                        .HasDatabaseName("ux_ps_player_state");

                    b.HasIndex("StateId", "Power")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ps_power");

                    b.HasIndex("StateId", "TileX", "TileY")
                        .HasDatabaseName("ix_ps_tile");

                    b.ToTable("player_states", (string)null);
                });

            modelBuilder.Entity("ZeroHour.Server.Data.PlayerState", b =>
                {
                    b.HasOne("ZeroHour.Server.Data.Player", "Player")
                        .WithMany("States")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ZeroHour.Server.Data.Player", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
